workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master

version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/dantoml/branchbot
    steps:
      - checkout
      - run: make build

  release:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/dantoml/branchbot
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Docker Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Docker Release
          command: |
            BUILD_NUM=$CIRCLE_BUILD_NUM make docker-release

      - store_artifacts:
          path: /go/src/github.com/dantoml/branchbot/build/release
          destination: binaries
